### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by PFight** [981377660LMT/vscode-plugin#1]
You are directly using https://github.com/google/intermock (even code sample from it), but no any mention about this. Not nice.

**Comment by 981377660LMT** [comment]
Sorry, I will indicate the source &nbsp;https://github.com/google/intermock.If needed I will unpublish&nbsp;this plugin based on your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "981377660LMT/vscode-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[981377660LMT/vscode-plugin] Copyright issue (#1)





 
You are directly using https://github.com/google/intermock (even code sample from it), but no any mention about this. Not nice.
